# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PromoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Networking
  pod 'Alamofire'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  
  # Reactive
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Moya-ObjectMapper/RxSwift'
  
  # switf utils
  pod 'Swinject'
  
  # Pods for PromoTest

  target 'PromoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PromoTestUITests' do
    # Pods for testing
  end

end
